### ISSUE TITLE
小瑕疵

### ISSUE THREAD

**Issue by 66one66** [SiriusFHJ/ShangAnNotes#1]
资料分析中有道题解析过程及结果是错误的
年均增长率
【例1】 某公司 2024 年营业收入为 100 亿元，预计营收年均增长率为10%，则 2018 年销售额为 ( ) 亿元。
解析：
100×(1+10%)3=133.1
100×(1+10%) 3 =133.1
100×（1+10%）3=133.1100 \times （1+10\%）^3 = 133.1100×（1+10%）3=133.1

**Comment by SiriusFHJ** [comment]
感谢反馈，已修复
